pid_file: "/var/run/tokeping.pid"

probes:
  - name: ping-cloudflare-dns-1-v6
    type: ping
    target: 2606:4700:4700::1111
    interval: 30s
  - name: ping-cloudflare-dns-v4
    type: ping
    target: 1.1.1.1
    interval: 30s
  - name: ping-cloudflare-dns-2-v6
    type: ping
    target: 2606:4700:4700::1001
    interval: 30s
  - name: ping-cloudflare-dns-2-v4
    type: ping
    target: 1.0.0.1
    interval: 30s
  - name: dns-qosbox
    type: dns
    target: dns.qosbox.com
    interval: 30s       
outputs:
  - name: local-ws
    type: ws
    listen: ":8080"
  - name: influx
    type: influxdb
    url: "http://localhost:8086"
    token: "my-token"
    org: "my-org"
    bucket: "metrics"
  - name: zmq
    type: zmq
    listen: "tcp://127.0.0.1:5556"
  - name: log-file
    type: file
    path: "/var/log/tokeping/metrics.log"
