pid_file: "/var/run/tokeping.pid"

probes:
# ------ Example mtr probe
probes:
  - name: mtr-ipv6-google
    type: mtr
    target: ipv6.google.com
    interval: 30s

# ------ Original Working Probes
  - name: ping-cloudflare-dns-1-v6
    type: ping
    target: 2606:4700:4700::1111
    interval: 30s

  - name: ping-cloudflare-dns-v4
    type: ping
    target: 1.1.1.1
    interval: 30s

  - name: ping-cloudflare-dns-2-v6
    type: ping
    target: 2606:4700:4700::1001
    interval: 30s

  - name: ping-cloudflare-dns-2-v4
    type: ping
    target: 1.0.0.1
    interval: 30s

  - name: dns-qosbox-cf1-v6
    type: dns
    target: dns.qosbox.com
    interval: 30s
    protocol: tcp    
    resolver: "[2606:4700:4700::1111]:53"

  - name: dns-qosbox-cf1-v6
    type: dns
    target: dns.qosbox.com
    interval: 30s
    protocol: udp # System default    
    resolver: "[2606:4700:4700::1111]:53"

  - name: dns-qosbox-cf1-dot-v6
    type: dns
    target: dns.qosbox.com
    interval: 30s
    protocol: dot    
    resolver: "[2606:4700:4700::1111]:853"

  - name: dns-qosbox-cf2-v6
    type: dns
    target: dns.qosbox.com
    interval: 30s    
    resolver: "[2606:4700:4700::1001]:53"

  - name: dns-qosbox-cf1-v4
    type: dns
    target: dns.qosbox.com
    interval: 30s    
    resolver: "1.1.1.1:53"

  - name: dns-qosbox-cf2-v4
    type: dns
    target: dns.qosbox.com
    interval: 30s    
    resolver: "1.0.0.1:53"

# Need to better test other DoH Systems
  - name: dns-doh-cloudflare
    type: dns
    target: dns.qosbox.com
    interval: 30s
    protocol: doh
    doh_url: "https://cloudflare-dns.com/dns-query"      

outputs:
  - name: local-ws
    type: ws
    listen: ":8080"
outputs:
  - name: influx
    type: influxdb
    url: "http://localhost:8086"
    token: "addyourownrandomtokenblahblah"
    org:   "tokeping-org"
    bucket: "metrics"
  - name: zmq
    type: zmq
    listen: "tcp://127.0.0.1:5556"
  - name: log-file
    type: file
    path: "/var/log/tokeping/metrics.log"
